repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: flake8
      args: ["--ignore=E203,E231,E501,W503"]
    - id: no-commit-to-branch
    - id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
      additional_dependencies: ['toml']
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
