language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install -v
  - pip install tox-travis codecov
script:
  - tox
after_success: codecov

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
